### PR TITLE
Changed wiki contents

### PR DESCRIPTION
**Pull request by ErwanH29**
Modified the data + location of lectures, along with the contact information.

### CODE REVIEW

**Comment by rieder** [comment]
The contents don't seem to match the title?

**Comment by ErwanH29** [comment]
From what I've seen Github doesn't allow a simple edit to the wiki. Any merge between branches needs some change to the code, so I edited the first typo I saw. Unless I am mistaken, the updated wiki should have updates on the location + dates of the lectures.

**Comment by rieder** [comment]
I think @spzwart needs to give you permission to edit the wiki. A PR won't do it...

**Comment by ErwanH29** [comment]
Ah, that's what I was thinking but wasn't sure so I gave it a shot anyways.
Thank you and sorry about that.

**Pull request closed without merging**
